"""rename receiver to recipient

Revision ID: 88d72ceb8fa9
Revises: f97d3cee1eba
Create Date: 2026-05-29 12:00:47.436933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d72ceb8fa9'
down_revision: Union[str, Sequence[str], None] = 'f97d3cee1eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_for_recipient', sa.String(), nullable=True))
    op.drop_column('messages', 'content_for_receiver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_for_receiver', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'content_for_recipient')
    # ### end Alembic commands ###
