"""added private key column

Revision ID: ed0f3b55f7fe
Revises: 88d72ceb8fa9
Create Date: 2026-06-01 12:52:23.081829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0f3b55f7fe'
down_revision: Union[str, Sequence[str], None] = '88d72ceb8fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_private_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_private_key')
    # ### end Alembic commands ###
