"""initial migration

Revision ID: f97d3cee1eba
Revises: 
Create Date: 2026-05-28 15:47:26.303299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97d3cee1eba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_for_sender', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('content_for_receiver', sa.String(), nullable=True))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'content_for_receiver')
    op.drop_column('messages', 'content_for_sender')
    # ### end Alembic commands ###
